# Generated by Django 3.1.7 on 2021-07-15 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='act_to_stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.CharField(max_length=128)),
                ('act_name', models.CharField(max_length=64)),
                ('act_start_time', models.DateField(default=1968)),
                ('act_end_time', models.DateField(default=1968)),
                ('act_organizer_name', models.CharField(max_length=64, null=True)),
                ('act_organizer_phone', models.CharField(max_length=32)),
                ('act_type', models.IntegerField()),
                ('act_created_team_number', models.IntegerField(null=True)),
                ('act_max_team_number', models.IntegerField(null=True)),
                ('act_min_team_number', models.IntegerField(null=True)),
                ('act_team_number', models.IntegerField(null=True)),
                ('act_state', models.IntegerField(null=True)),
                ('act_total_number', models.IntegerField(null=True)),
                ('act_participated_number', models.IntegerField(null=True)),
                ('act_available_team_number', models.IntegerField(null=True)),
                ('act_available_number', models.IntegerField(null=True)),
                ('act_flag', models.CharField(max_length=16)),
                ('act_planning_book', models.FileField(null=True, upload_to='')),
                ('act_introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='activities_modified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.CharField(max_length=128)),
                ('act_name', models.CharField(max_length=64)),
                ('act_start_time', models.DateField(default=1968)),
                ('act_end_time', models.DateField(default=1968)),
                ('act_organizer_name', models.CharField(max_length=64, null=True)),
                ('act_organizer_phone', models.CharField(max_length=32)),
                ('act_type', models.IntegerField()),
                ('act_created_team_number', models.IntegerField()),
                ('act_max_team_number', models.IntegerField()),
                ('act_min_team_number', models.IntegerField()),
                ('act_team_number', models.IntegerField()),
                ('act_state', models.IntegerField()),
                ('act_total_number', models.IntegerField()),
                ('act_participated_number', models.IntegerField()),
                ('act_available_number', models.IntegerField()),
                ('act_flag', models.CharField(max_length=16)),
                ('act_planning_book', models.FileField(null=True, upload_to='')),
                ('act_introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_id', models.CharField(max_length=64)),
                ('man_password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=64)),
                ('notices_create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('notice_content', models.TextField()),
                ('notice_appendix', models.FileField(null=True, upload_to='')),
                ('notice_tag', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='organizers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=64)),
                ('org_name', models.CharField(max_length=64)),
                ('org_header_name', models.CharField(max_length=64)),
                ('org_password', models.CharField(max_length=128)),
                ('org_header_phone', models.CharField(max_length=32)),
                ('org_header_college', models.CharField(max_length=128, null=True)),
                ('org_introduction', models.TextField()),
                ('org_valid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='organizers_modified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=64)),
                ('org_password', models.CharField(max_length=128)),
                ('org_name', models.CharField(max_length=64)),
                ('org_header_name', models.CharField(max_length=64)),
                ('org_header_phone', models.CharField(max_length=32)),
                ('org_introduction', models.TextField()),
                ('org_valid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stu_to_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=64)),
                ('stu_name', models.CharField(max_length=64)),
                ('stu_password', models.CharField(max_length=128)),
                ('stu_Email', models.EmailField(max_length=64)),
                ('stu_phone', models.CharField(max_length=32, null=True)),
                ('stu_gender', models.CharField(max_length=8)),
                ('stu_college', models.CharField(max_length=128, null=True)),
                ('stu_major', models.CharField(max_length=128, null=True)),
                ('stu_grade', models.IntegerField(null=True)),
                ('stu_introduction', models.TextField(null=True)),
                ('stu_valid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('team_name', models.CharField(max_length=64, null=True)),
                ('team_header_name', models.CharField(max_length=64)),
                ('team_header_phone', models.CharField(max_length=32)),
                ('team_introduction', models.CharField(max_length=256, null=True)),
                ('team_act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sac_app.activities')),
                ('team_members', models.ManyToManyField(through='sac_app.stu_to_team', to='sac_app.students')),
            ],
        ),
        migrations.AddField(
            model_name='stu_to_team',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sac_app.students'),
        ),
        migrations.AddField(
            model_name='stu_to_team',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sac_app.teams'),
        ),
        migrations.AddField(
            model_name='activities',
            name='act_organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sac_app.organizers'),
        ),
        migrations.AddField(
            model_name='activities',
            name='act_to_stu_table',
            field=models.ManyToManyField(through='sac_app.act_to_stu', to='sac_app.students'),
        ),
        migrations.AddField(
            model_name='act_to_stu',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sac_app.activities'),
        ),
        migrations.AddField(
            model_name='act_to_stu',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sac_app.students'),
        ),
    ]
