# Generated by Django 3.1.7 on 2021-07-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizers_modified',
            name='org_header_college',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizers_modified',
            name='org_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
