# Generated by Django 3.1.7 on 2021-07-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac_app', '0002_auto_20210715_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities_modified',
            name='act_valid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
