# Generated by Django 3.1.7 on 2021-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac_app', '0003_activities_modified_act_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='org_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
